name: fetch-crowdin

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Install overcrowdin
      run: dotnet tool update -g overcrowdin || dotnet tool install -g overcrowdin
    - name: Crowdin settings
      run: |
        tee crowdin.json <<< '
          {
            \"project_identifier\": \"fieldworks\", 
            \"api_key_env\": \"CROWDIN_API_KEY\", 
            \"base_path\": \".\", 
            \"branch\": \"FieldWorks-9.0\",
          }
        '
    - name: Download crowdin localizations
      env:
        CROWDIN_API_KEY: ${{ secrets.CROWDIN_API_KEY }}
      run: overcrowdin download -v -r2 -f crowdin.zip
