name: fetch-crowdin

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Install overcrowdin
      run: dotnet tool install -g overcrowdin
    - name: Crowdin settings
      run: |
        tee crowdin.json <<< '
          {
            "project_identifier": "fieldworks",
            "api_key_env": "CROWDIN_API_KEY",
            "base_path": ".",
            "branch": "FieldWorks-9.0",
          }
        '
    - name: Download crowdin localizations
      env:
        CROWDIN_API_KEY: ${{ secrets.CROWDIN_API_KEY }}
      # TODO crowdin localizations are provided for multiple branches. So fetch
      # and provide from multiple branches.
      run: |
        overcrowdin download -v -r2 -f crowdin.zip
        mkdir artifacts
        mv crowdin.zip artifacts/
    - name: Determine build version
      run: |
        set -xueo pipefail
        git fetch --unshallow
        BUILD_VERSION=$(git describe)
        TAG_NAME=$(git describe|perl -p -e 's/FieldWorks/v/')
        # Set BRANCH_NAME to the branch targetted by a PR, if this is a PR, or to
        # the name of the current branch, if this is not a PR. eg 'refs/heads/develop'.
        BRANCH_NAME=${{github.base_ref}}
        [[ -n ${BRANCH_NAME} ]] || BRANCH_NAME=${{github.ref}}
        echo >> "${GITHUB_ENV}" "BUILD_VERSION=${BUILD_VERSION}"
        echo >> "${GITHUB_ENV}" "TAG_NAME=${TAG_NAME}"
        echo >> "${GITHUB_ENV}" "BRANCH_NAME=${BRANCH_NAME}"
    - name: Publish artifacts as Github release
      uses: ncipollo/release-action@v1.8.6
      with:
        artifacts: "artifacts/*"
        prerelease: false
        # Branch to build from
        commit: "${{ env.BRANCH_NAME }}"
        # Name of new tag to be created
        tag: "${{ env.TAG_NAME }}"
        allowUpdates: true
        artifactErrorsFailBuild: true
        # Name of release
        name: "${{env.TAG_NAME}}-${{env.BRANCH_NAME}}"
        body: "Crowdin localizations"
        token: ${{ secrets.GITHUB_TOKEN }}
